package ot.scalaotl
package commands

import org.apache.spark.sql.DataFrame
import org.apache.spark.sql.functions.lit

/** =Abstract=
 * This class provides support of __'''addinfo'''__ otl command.
 *
 * __'''addinfo'''__ adds fields containing general information about the request ID
 *
 * and the time intervals for which the results of the request were received.
 *
 * __'''addinfo'''__ takes no arguments.
 *
 * __'''addinfo'''__ add fields '''info_min_time''' - earliest time boundary to search (__tws__),
 *
 * '''info_max_time''' - latest time boundary to search (__twf__),
 *
 * '''info_sid''' - the ID of the search generated by event (__searchId__).
 *
 * =Usage example=
 * OTL:
 * {{{makeresults count = 5 | eval a = 1 | eval b = 2 | addinfo}}}
 *
 * Result:
 *{{{+----------+---+---+-------------+-------------+--------+
|     _time|  a|  b|info_min_time|info_max_time|info_sid|
+----------+---+---+-------------+-------------+--------+
|1645709088|  1|  2|            0|            0|     317|
|1645709088|  1|  2|            0|            0|     317|
|1645709088|  1|  2|            0|            0|     317|
|1645709088|  1|  2|            0|            0|     317|
|1645709088|  1|  2|            0|            0|     317|
+----------+---+---+-------------+-------------+--------+}}}
 *
 * @constructor creates new instance of [[OTLAddinfo]]
 * @param sq [[SimpleQuery]]
 */
class OTLAddinfo(sq: SimpleQuery) extends OTLBaseCommand(sq) {
  val requiredKeywords = Set.empty[String]
  val optionalKeywords = Set.empty[String]
  val id: Int = sq.searchId
  val tws: Int = sq.tws
  val twf: Int = sq.twf

  override def fieldsGenerated = List("info_min_time", "info_max_time", "info_sid")

  /**
   * @param _df input __dataframe__, passed by the [[Converter]] when executing an OTL query
   * @return _df with '''info_min_time''' (__tws__), '''info_max_time''' (__twf__),
   *         '''info_sid''' (__searchId__) fields
   */
  override def transform(_df: DataFrame): DataFrame = {
    _df.withColumn("info_min_time", lit(tws))
      .withColumn("info_max_time", lit(twf))
      .withColumn("info_sid", lit(id))
  }
}
